// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageProcessorClient is the client API for ImageProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageProcessorClient interface {
	ApplyFilter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	ResizeImage(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error)
	RemoveBackground(ctx context.Context, in *BackgroundRemovalRequest, opts ...grpc.CallOption) (*BackgroundRemovalResponse, error)
	GetImageInfo(ctx context.Context, in *ImageInfoRequest, opts ...grpc.CallOption) (*ImageInfoResponse, error)
}

type imageProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewImageProcessorClient(cc grpc.ClientConnInterface) ImageProcessorClient {
	return &imageProcessorClient{cc}
}

func (c *imageProcessorClient) ApplyFilter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, "/image_processing.ImageProcessor/ApplyFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageProcessorClient) ResizeImage(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error) {
	out := new(ResizeResponse)
	err := c.cc.Invoke(ctx, "/image_processing.ImageProcessor/ResizeImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageProcessorClient) RemoveBackground(ctx context.Context, in *BackgroundRemovalRequest, opts ...grpc.CallOption) (*BackgroundRemovalResponse, error) {
	out := new(BackgroundRemovalResponse)
	err := c.cc.Invoke(ctx, "/image_processing.ImageProcessor/RemoveBackground", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageProcessorClient) GetImageInfo(ctx context.Context, in *ImageInfoRequest, opts ...grpc.CallOption) (*ImageInfoResponse, error) {
	out := new(ImageInfoResponse)
	err := c.cc.Invoke(ctx, "/image_processing.ImageProcessor/GetImageInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageProcessorServer is the server API for ImageProcessor service.
// All implementations must embed UnimplementedImageProcessorServer
// for forward compatibility
type ImageProcessorServer interface {
	ApplyFilter(context.Context, *FilterRequest) (*FilterResponse, error)
	ResizeImage(context.Context, *ResizeRequest) (*ResizeResponse, error)
	RemoveBackground(context.Context, *BackgroundRemovalRequest) (*BackgroundRemovalResponse, error)
	GetImageInfo(context.Context, *ImageInfoRequest) (*ImageInfoResponse, error)
	mustEmbedUnimplementedImageProcessorServer()
}

// UnimplementedImageProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedImageProcessorServer struct {
}

func (UnimplementedImageProcessorServer) ApplyFilter(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyFilter not implemented")
}
func (UnimplementedImageProcessorServer) ResizeImage(context.Context, *ResizeRequest) (*ResizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeImage not implemented")
}
func (UnimplementedImageProcessorServer) RemoveBackground(context.Context, *BackgroundRemovalRequest) (*BackgroundRemovalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBackground not implemented")
}
func (UnimplementedImageProcessorServer) GetImageInfo(context.Context, *ImageInfoRequest) (*ImageInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageInfo not implemented")
}
func (UnimplementedImageProcessorServer) mustEmbedUnimplementedImageProcessorServer() {}

// UnsafeImageProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageProcessorServer will
// result in compilation errors.
type UnsafeImageProcessorServer interface {
	mustEmbedUnimplementedImageProcessorServer()
}

func RegisterImageProcessorServer(s grpc.ServiceRegistrar, srv ImageProcessorServer) {
	s.RegisterService(&ImageProcessor_ServiceDesc, srv)
}

func _ImageProcessor_ApplyFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageProcessorServer).ApplyFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/image_processing.ImageProcessor/ApplyFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageProcessorServer).ApplyFilter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageProcessor_ResizeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageProcessorServer).ResizeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/image_processing.ImageProcessor/ResizeImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageProcessorServer).ResizeImage(ctx, req.(*ResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageProcessor_RemoveBackground_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackgroundRemovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageProcessorServer).RemoveBackground(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/image_processing.ImageProcessor/RemoveBackground",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageProcessorServer).RemoveBackground(ctx, req.(*BackgroundRemovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageProcessor_GetImageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageProcessorServer).GetImageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/image_processing.ImageProcessor/GetImageInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageProcessorServer).GetImageInfo(ctx, req.(*ImageInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageProcessor_ServiceDesc is the grpc.ServiceDesc for ImageProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "image_processing.ImageProcessor",
	HandlerType: (*ImageProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyFilter",
			Handler:    _ImageProcessor_ApplyFilter_Handler,
		},
		{
			MethodName: "ResizeImage",
			Handler:    _ImageProcessor_ResizeImage_Handler,
		},
		{
			MethodName: "RemoveBackground",
			Handler:    _ImageProcessor_RemoveBackground_Handler,
		},
		{
			MethodName: "GetImageInfo",
			Handler:    _ImageProcessor_GetImageInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/image_processing.proto",
}
